#include "continuous_runtime.h"
#include <filesystem>
#include <fstream>
#include <string>
namespace fs=std::filesystem;
static std::string q(const std::string& s){std::string r="\"";for(char c:s){if(c=='\"'||c=='\\')r+='\\';r+=c;}return r+"\"";}
static void facts(std::ostream& o,const Observation& x){o<<"[";for(size_t i=0;i<x.facts.size();++i){if(i)o<<",";o<<"{\"key\":"<<q(x.facts[i].key)<<",\"value\":"<<q(x.facts[i].value)<<"}";}o<<"]";}
static void candidates(std::ostream& o,const DecisionContext& d){o<<"[";for(size_t i=0;i<d.candidates.size();++i){if(i)o<<",";auto& c=d.candidates[i];o<<"{\"action\":"<<q(to_string(c.action))<<",\"target\":"<<q(c.target_object_id)<<",\"probability\":"<<c.probability<<",\"eligible\":"<<(c.eligible?"true":"false")<<"}";}o<<"]";}
static void action(std::ostream& o,const std::optional<RunningAction>& a){if(!a){o<<"null";return;}o<<"{\"action\":"<<q(to_string(a->action))<<",\"target\":"<<q(a->target_object_id)<<",\"elapsed\":"<<a->elapsed_minutes<<",\"planned\":"<<a->planned_duration_minutes<<"}";}
int main(int argc,char**v){if(argc<4)return 2;unsigned ss=std::stoul(v[1]),ps=std::stoul(v[2]);fs::path p=v[3];fs::create_directories(p.parent_path());std::ofstream o(p);World w(ss);w.time.minute_of_day=480;Observation ob=refresh_observation({},w,{});RuntimeScheduler sch(480);ContinuousRuntime rt(sch,w,ob,{},ps);CharacterState s;Personality per;rt.submit_action_intent(ActionType::Idle,"",10);o<<"[";for(int i=0;i<36;++i){if(i)o<<",";auto r=rt.execute_next_boundary(s,per);o<<"{\"timestamp\":"<<sch.now_total_minutes()<<",\"elapsed\":"<<r.runtime.boundary.elapsed_minutes<<",\"scenario_seed\":"<<ss<<",\"policy_seed\":"<<ps<<",\"bootstrap\":"<<(i==0?"true":"false")<<",\"observation\":{\"facts\":";facts(o,ob);o<<",\"known_actions\":";o<<"[";for(size_t j=0;j<ob.known_actions.size();++j){if(j)o<<",";o<<q(to_string(ob.known_actions[j]));}o<<"]},\"world_events\":[";for(size_t j=0;j<r.runtime.world_events.size();++j){if(j)o<<",";o<<"{\"id\":"<<q(r.runtime.world_events[j].id)<<"}";}o<<"],\"observation_deltas\":[";for(size_t j=0;j<r.observation_deltas.size();++j){if(j)o<<",";o<<"{\"key\":"<<q(r.observation_deltas[j].key)<<",\"value\":"<<q(r.observation_deltas[j].value)<<"}";}o<<"],\"candidates\":";candidates(o,r.decision);o<<",\"decision_gate\":{\"open\":"<<(r.runtime.boundary.decision_gate.open?"true":"false")<<"},\"policy_evaluated\":"<<(r.policy_evaluated?"true":"false")<<",\"running_action_before\":";action(o,r.running_action_before);o<<",\"running_action_after\":";action(o,r.running_action_after);o<<",\"selected_action\":"<<(r.selected_action?q(to_string(*r.selected_action)):"null")<<",\"task_effort\":"<<w.tasks.front().effort_done<<",\"hunger\":"<<s.hunger<<",\"fatigue\":"<<s.fatigue<<",\"bathroom_urge\":"<<s.bathroom_urge<<"}";}o<<"]\n";}
