import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '../../../_local_data/native_platform_v0/ensemble');
const example = path.join(root, 'examples/loversAndRivals');
const names = ['schema', 'cast', 'triggerRules', 'volitionRules', 'actions', 'history'];
const raw = Object.fromEntries(names.map(n => [n, fs.readFileSync(path.join(example, 'data', `${n}.json`), 'utf8')]));
const ctx = { console: { log() {}, warn() {}, error() {} } };
vm.createContext(ctx);
const data = vm.runInContext(`Object.fromEntries(Object.entries(${JSON.stringify(raw)}).map(([k,v]) => [k, JSON.parse(v)]))`, ctx);
vm.runInContext(fs.readFileSync(path.join(example, 'ensemble.js'), 'utf8'), ctx, { filename: 'official ensemble.js' });
const e = ctx.ensemble;
e.init();
e.loadSocialStructure(data.schema);
const cast = e.addCharacters(data.cast);
e.addRules(data.triggerRules);
e.addRules(data.volitionRules);
e.addActions(data.actions);
e.addHistory(data.history);

const steps = [];
const volitions = e.calculateVolition(cast);
const intent = volitions.getFirst('hero', 'love');
steps.push({ step: 'calculateVolition', target: ['hero', 'love'], result: intent });
const actions = e.getActions('hero', 'love', volitions, cast, 20, 100);
const chosen = actions.find(a => a.name === 'writeLoveNoteReject');
if (!chosen) throw new Error('expected original action binding writeLoveNoteReject missing');
steps.push({ step: 'getActions', candidates: actions.map(a => ({ name: a.name, weight: a.weight, lineage: a.lineage })), chosen: chosen.name });
const pre = JSON.parse(JSON.stringify(e.getSocialRecordCopyAtTimestep()));
e.doAction(chosen);
const afterAction = JSON.parse(JSON.stringify(e.getSocialRecordCopyAtTimestep()));
steps.push({ step: 'doAction', effectsObserved: afterAction.filter(p => !pre.some(q => q.id === p.id)).map(({ category, type, first, second, value }) => ({ category, type, first, second, value })) });
e.runTriggerRules(cast);
const afterTrigger = JSON.parse(JSON.stringify(e.getSocialRecordCopyAtTimestep()));
steps.push({ step: 'explicitTrigger', effectsObserved: afterTrigger.filter(p => !afterAction.some(q => q.id === p.id)).map(({ category, type, first, second, value }) => ({ category, type, first, second, value })) });
e.setupNextTimeStep();
steps.push({ step: 'setupNextTimeStep', currentTimeStep: e.getCurrentTimeStep(), record: JSON.parse(JSON.stringify(e.getSocialRecordCopyAtTimestep())) });
process.stdout.write(JSON.stringify({ source: 'official browser example data and bundled engine', actionsChosen: chosen.name, steps }, null, 2) + '\n');
